name: Deploy Laravel (in subfolder) to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_pgsql

      - name: Install Composer Dependencies
        run: |
          cd laravel
          composer install --no-dev --optimize-autoloader

      - name: Generate Laravel Key (optional)
        run: |
          cd laravel
          php artisan config:clear
          php artisan key:generate
        env:
          APP_KEY: ${{ secrets.APP_KEY }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: laravel-webgis
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./laravel
