name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_pgsql
          tools: composer

      - name: Install PHP dependencies
        run: |
          cd laravel
          composer install --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies and build assets
        run: |
          cd laravel
          npm install
          npm run build

      - name: Prepare deployment folder
        run: |
          mkdir deploy-folder
          cp -r laravel/* deploy-folder/
          cp -r laravel/.* deploy-folder/ || echo "No hidden files"
          ls -la deploy-folder

      - name: Zip deployment folder
        run: |
          cd deploy-folder
          zip -r ../deploy.zip .

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Laravel to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: laravel-webgis
          package: deploy.zip
